NumPy - Numarical Python

Advantages of NUmpy arrays:

1.Allow several Mathmatical Operations
2.Faster operations

In [11]:
#importing
import numpy as np

List vs Numpy - Time taken

In [12]:
from time import process_time


Time taken by a List

In [16]:
python_list = [i for i in range(10000)]

start_time = process_time()
python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0014943800000004615


In [17]:
nparray = np.array([i for i in range(10000)])

start_time = process_time()

nparray += 5

end_time = process_time()

print(end_time - start_time)

0.00032465299999984154


NumPy arrays

In [18]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [19]:
#np array

np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [20]:
# creating a 1d array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [21]:
a.shape

(5,)

In [22]:
b = np.array([[1,2,3],[3,5,6]])
print(b)

[[1 2 3]
 [3 5 6]]


In [23]:
b.shape

(2, 3)

In [24]:
c =np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Place holders in numpy array

In [25]:
#create numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
#create a numpy array of ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# array of a perticular value

z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [28]:
# create an identity matrix
a= np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
 #create a numpy array with random values

b = np.random.random((3,4))
print(b)

[[0.82422753 0.10033568 0.97417466 0.99711889]
 [0.55179811 0.40061361 0.98390925 0.94506451]
 [0.63465252 0.37896513 0.90889206 0.29169241]]


In [32]:
# random values arrray
c = np.random.randint(10,100,(3,5))
print(c)


[[75 23 15 70 40]
 [30 10 47 43 89]
 [61 25 28 77 34]]


In [36]:
#array of evenly spaced values spacifying the number of values
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [38]:
# array of evenly spaced values spacifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [39]:
#convert a list to an array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing NumPy array

In [40]:
c = np.random.randint(10,90,(5,5))
print(c)

[[73 76 58 72 76]
 [55 53 30 55 80]
 [33 21 61 78 82]
 [27 79 63 26 20]
 [64 81 82 47 22]]


In [41]:
# array dimension
print(c.shape)

(5, 5)


In [42]:
#number of dimentions
print(c.ndim)

2


In [43]:
#checking the number of elements in an array
print(c.size)

25


In [44]:
# checking the data type of values in the array
print(c.dtype)

int64


Mathematical operations in np array

In [45]:
list1 = [1,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) #concatenate or join two list

[1, 3, 4, 5, 6, 7, 8, 9, 10]


In [47]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)


[[5 1 0]
 [4 7 2]
 [5 7 7]]
[[16 12 14]
 [14 17 17]
 [17 15 16]]
[[21 13 14]
 [18 24 19]
 [22 22 23]]


In [48]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[21 13 14]
 [18 24 19]
 [22 22 23]]
[[-11 -11 -14]
 [-10 -10 -15]
 [-12  -8  -9]]
[[ 80  12   0]
 [ 56 119  34]
 [ 85 105 112]]
[[0.3125     0.08333333 0.        ]
 [0.28571429 0.41176471 0.11764706]
 [0.29411765 0.46666667 0.4375    ]]


In [50]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 13 14]
 [18 24 19]
 [22 22 23]]
[[-11 -11 -14]
 [-10 -10 -15]
 [-12  -8  -9]]
[[ 80  12   0]
 [ 56 119  34]
 [ 85 105 112]]
[[0.3125     0.08333333 0.        ]
 [0.28571429 0.41176471 0.11764706]
 [0.29411765 0.46666667 0.4375    ]]


Array Manipulation

In [51]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 6 6]
 [2 8 4]]
(2, 3)


In [52]:
#transpose

trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 2]
 [6 8]
 [6 4]]
(3, 2)


In [53]:
trans2 = array.T #another way
print(trans2)
print(trans2.shape)

[[1 2]
 [6 8]
 [6 4]]
(3, 2)


In [54]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[1 8 0]
 [6 3 1]]
(2, 3)


In [55]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 8]
 [0 6]
 [3 1]]
(3, 2)
